---
vecnet_deploy_root: /opt/vecnet-dl
rails_env: development
fedora_password: fedoraAdmin
solr_service_addr: http://localhost:8081/solr
db_hostname: localhost
vecnet_db_name: vecnet_db
vecnet_db_user: vecnet
vecnet_db_pass: XXX
